[package]
name = "hdfspp-sys"
version = "0.1.0"
edition = "2021"
description = "Rust bindings for hdfspp, the CPP client for HDFS"
license = "Apache-2.0"
repository = "https://github.com/Xuanwo/hdfspp-sys"

[dependencies]
